config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :posts do
    resources :replies
  end
  resources :users
  root "posts#index"
  get 'posts/:user' => 'posts#index', as: "user_posts"
  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"
  # post "/posts/:index/reply", to: "replies#create", as: "reply_to_post"
  # post "/replies/new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :replies
  # before_save :check_session_user_id
  validates_presence_of :title, :text
  belongs_to :user, optional: true
  has_many :replies
  # def valid?
  #  self.user_id = session[:user_id]
  #  super
  # end
end

app/models/reply.rb
class Reply < ApplicationRecord
  validates_presence_of :user_id, :text
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if (params[:user])
      @posts = Post.where("user_id = ?", User.find_by(name: params[:user]).id);
    else 
      @posts = Post.all
    end
    @posts.each { |post| post.replies = Reply.where(post_id: post.id) }


  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id] if session[:user_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @post.replies = Reply.where(post_id: @post.id)
      @replies = @post.replies
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end

    def set_replies
      @post.replies = Reply.where(post_id: @post.id)
    end

    def set_all_replies
      @posts.each { |post| post.replies = Reply.where(post_id: post.id) }
    end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  

  def new
    @reply = Reply.new
  end

  def create
    @reply = Reply.new(reply_params)
    @reply.post_id = params[:post_id]
    @reply.user_id = session[:user_id]
    # @reply.user_id = session[:user_id] if session[:user_id]
    @reply.save
    redirect_back fallback_location: posts_path
  end

  def destroy
    Reply.destroy(params[:id])
    redirect_back fallback_location: posts_path
  end

  private

  def reply_params
    params.require(:reply).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if (user && user.password == (params[:session][:password]))
      session[:user_id] = user.id
      redirect_to posts_url
    else
      render 'new' 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user.posts = Post.where(user_id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    session[:user_id] = @user.id
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :info, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def has_replies?(post)
    Reply.where(post_id: post.id).size == 0? false: true
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Msgr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-header container">
      <h1 class="pull-left"><%=link_to "msgr", posts_path %><small> featuring a compelling sub header</small></h1>
      <% if session[:user_id] != nil %>
        <h1 class="pull-right"><small>User: <%= link_to User.find(session[:user_id]).name, user_path(session[:user_id]) %> | <%= link_to "Log out", logout_path, method: :delete, id: "sign-out" %></small></h1>
      <% else %>
        <h3 class="pull-right"><%=link_to "Log in", login_path%> | <%= link_to "Sign Up", new_user_path %></h3>
      <% end %>
    </div>
    
    <div class="container" id="body">
      <div class="alert alert-success alert-dismissible hidden" id="sign-out-alert" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
        You have been signed out.
    </div>
      <%= yield %>
    </div>
    <% console %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title , {class: "form-control"} %>
  </div>

  <div class="field form-group">
    <%= f.label :text %>
    <%= f.text_area :text, {class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/_replies.html.erb
  <% replies.each do |reply| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <p> <%= reply.text %> </p>
        <%= link_to "By #{User.find(reply.user_id).name}", users_path(reply.user_id) %>
        <% if session[:user_id] == reply.user_id %>
          <%= link_to "Delete", post_reply_path(post_id: post.id, id: reply.id), method: :delete, class: "pull-right" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/posts/_reply.html.erb
<%# = form_for @replies.new(user_id: session[:user_id]), url: new_post_reply_path(post_id: @post.id) do |f| %>
<%= form_for @post.replies.new, url: post_replies_path(@post.id) do |f| %>
  <div class="field form-group">
    <%=f.text_area :text, class: "form-control" %>
    <%=f.submit "Reply", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Posts</h2>
<% if (@posts.count == 0) %>
  <p>There are no posts to display.</p>
<% end %>
<%= link_to 'New Post', new_post_path %>
<% @posts.order(created_at: :DESC).each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to post.title, post, {class: "panel-title"} %>
    </div>
    <div class="panel-body">
      <p><%= post.text %></p>
      <p>Posted by <%= link_to "#{User.find(post.user_id).name}", User.find(post.user_id) %></p>
      <%= link_to 'Edit', edit_post_path(post), {class: "pull-right"}  if session[:user_id] == post.user_id %>
      <% if has_replies?(post) %>
          <a data-toggle="collapse" href="#post-<%="#{post.id}"%>-replies" aria-expanded="false" aria-controls=<%= "post-#{post.id}-replies"%>>Show Comments</a>
          <div class="collapse" id=<%="post-#{post.id}-replies"%>>          
            <div class="well">
              <%= render partial: "replies", object: Reply.where(post_id: post.id), locals: {post: post} %>
            </div>
          </div>
      <% else %>
        <p>No replies</p>
      <% end %>
    </div>
  </div>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to @post.title, @post, {class: "panel-title"} %>
  </div>
  <div class="panel-body">
    <p><%= @post.text %></p>
    Posted by <%= link_to "#{User.find(@post.user_id).name}", User.find(@post.user_id) %>
    <%= link_to 'Edit', edit_post_path(@post), {class: "pull-right"}  if session[:user_id] == @post.user_id %>
    <br>
    <br>
    <% if @post.replies.size > 0 %>
      <!--
        <% @post.replies.each do |reply| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <p> <%= reply.text %> </p>
              <%= link_to "By #{User.find(reply.user_id).name}", users_path(reply.user_id) %>
              <%= link_to "Delete", post_reply_path(post_id: @post.id, id: reply.id), method: :delete, class: "pull-right" %>
            </div>
          </div>
        <% end %>
      -->
      <p><strong>Replies:</strong></p>
      <div class="well">
        <%= render partial: "replies", object: @post.replies, locals: {post: @post} %>
      </div>
    <% else %>
      <p><strong>No replies yet.</strong></p>
    <% end %>
    <%= render partial: "reply" %>
  </div> 
</div>
<%= link_to "Back", post_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_field :info, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default"  %>
  </div>
<% end %>

app/views/users/_login.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, { class: "form-control" } %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password { class: "form-control" } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <%# <th>Password</th> %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.info %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.name %> <small><%= link_to 'Edit Profile', edit_user_path(@user) , class: "pull-right"%><small></h2>
 
<br>
<p>
  </strong><%= @user.info %></p>
<br>

<% if @user.posts.size > 0 %>
  <h2>Posts by <%= @user.name %> </h2>
<% end %>
<% @user.posts.order(created_at: :DESC).each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to post.title, post_path(post.id), class: "panel-title" %>
    </div>
    <div class="panel-body">
      <p> <%= post.text %> </p>
    </div>
  </div>
<% end %>